services:

#Seriço para a aplicação FastAPI
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    
    #Serviço para o banco de dados PostgreSQL
  db:
    image: postgres
    container_name: dbpostgres
    restart: always
    environment:
      POSTGRES_USER: postgres2025
      POSTGRES_PASSWORD: postgres2025
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 
volumes:
  pgdata: